server:
  port: 8080
spring:
  application:
    name: "Autogestion-Movil-ms"
  profiles:
    include: "local"
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: autogestion_schema
  sql:
    init:
      mode: "always"
  flyway:
    enabled: true
    locations: classpath:db/migration
    create-schemas: true
    baseline-on-migrate: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/autogestion_db?currentSchema=autogestion_schema
    username: postgres
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8082
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8082"
springdoc:
  use-management-port: true
jwt:
  secret: "secretsecretsecretsecretsecretsecretsecretsecret"
  expiration: 24

logging:
  level:
    org.flywaydb.core: DEBUG

